[global]
    width = 400
    offset = 5x5
    
    progress_bar_min_width = 380
    progress_bar_max_width = 380
    progress_bar_corner_radius = 2

    padding = 10
    horizontal_padding = 10
    frame_width = 3
    gap_size = 3
    font = "{{ vars.font_family }} 11"

    icon_theme = "{{ vars.theme_name }}"
    enable_recursive_icon_lookup = true
    corner_radius = 2

    background = "{{ vars.theme_base }}"
    foreground = "{{ vars.theme_text }}"

[urgency_low]
    background = "{{ vars.theme_base }}"
    highlight = "{{ vars.theme_iris }}"
    frame_color = "{{ vars.theme_iris }}"
    default_icon = "dialog-information"
    format = "<b><span foreground='{{ vars.theme_iris }}'>%s</span></b>\n%b"

[urgency_normal]
    background = "{{ vars.theme_foam }}"
    highlight = "{{ vars.theme_text }}"
    frame_color = "{{ vars.theme_pine }}"
    default_icon = "dialog-warning"
    format = "<b><span foreground='{{ vars.theme_overlay }}'>%s</span></b>\n%b"

[urgency_critical]
    background = "{{ vars.theme_rose }}"
    highlight = "{{ vars.theme_gold }}"
    frame_color = "{{ vars.theme_love }}"
    default_icon = "dialog-error"
    format = "<b><span foreground='{{ vars.theme_overlay }}'>%s</span></b>\n%b"