# Init Oh-my-zsh and path vars
export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$HOME/langs/roc/:$PATH"
export PATH="$HOME/langs/zig/:$PATH"
export HELIX_RUNTIME="$HOME/.config/helix/runtime"
. "$HOME/.cargo/env"

# Creature comforts
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HYPHEN_INSENSITIVE="true"

# fzf integration
source <(fzf --zsh)

# Init zsh plugins
fpath=(/usr/local/share/zsh-completions $fpath)
command -v brew &> /dev/null && FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
plugins=(direnv docker docker-compose fzf rust sbt scala ssh-agent zsh-autosuggestions zsh-syntax-highlighting)

# Fixes for plugins that dont want to work
source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source "$ZSH/oh-my-zsh.sh"

# To help programs that read these
export VISUAL=hx
export EDITOR="$VISUAL"

# jenv
command -v jenv &> /dev/null && eval "$(jenv init -)"

# Cause i'm tried of googling it & typing it, some utilities to
# Diff two csvs column wise
# List orphaned local branches 'cause they were merged remotely
# List touched files by grep pattern
alias csvdiff='git diff --color-words="[^[:space:],]+"'

# Aliases because some of these commands are just too easy to forget
alias mvn="mvn -T 4 -ntp"
alias kc="kubectl"
alias kn="kubens"
alias kx="kubectx"
alias ssh="kitty +kitten ssh -A"
alias spt="spotify_player"

# Load any extensions we have for this computer in the config
# directory (like werk stuff)
for conf in "$HOME/.config/zsh/"*.zsh; do
  source "${conf}"
done
unset conf

# Load linux specifics
if uname | grep -i linux &> /dev/null; then
  alias open='xdg-open'
  alias pbcopy='wl-copy'
  alias pbpaste='wl-paste'
fi

# Final inits. Note we -A SSH so identity is forwarded to remote server
command -v fnm &> /dev/null && eval "$(fnm env --use-on-cd --shell zsh)"
eval "$(starship init zsh)"

# Tab Completions
source <(jj util completion zsh)

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniforge/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniforge/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
