# Init Oh-my-zsh and path vars
export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$HOME/langs/roc/:$PATH"
export PATH="$HOME/langs/zig/:$PATH"
export HELIX_RUNTIME="$HOME/.config/helix/runtime"

export VISUAL=hx
export EDITOR="$VISUAL"

# mise -- all your devtools
# envs: home, home-linux, work, workbox
[ -f "$HOME/.mise_env" ] && source "$HOME/.mise_env"
command -v mise &> /dev/null && eval "$(mise activate zsh)"

# Creature comforts for omz settings
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HYPHEN_INSENSITIVE="true"

# Init zsh plugins
fpath=(/usr/local/share/zsh-completions $fpath)
command -v brew &> /dev/null && FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
plugins=(zsh-autosuggestions zsh-syntax-highlighting)
source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source "$ZSH/oh-my-zsh.sh"

if [[ "$TERM" == "xterm-kitty" ]]; then
  if [[ -n "$ZELLIJ" ]]; then
    alias ssh="TERM=xterm-256color ssh"
  else
    alias ssh="kitty +kitten ssh -A"
  fi
fi

# Load any extensions we have for this computer in the config
# directory (like werk stuff)
for conf in "$HOME/.config/zsh/"*.zsh; do
  source "${conf}"
done
unset conf

# Tool hooks
source <(fzf --zsh)

# Completions. These may want to be cached eventually
source <(jj util completion zsh)
source <(docker completion zsh)
source <(rustup completions zsh)

# Prompt line
eval "$(starship init zsh)"
