[templates]
# TODO: Wallust
# Note: When using themes, the {{wallpaper}} value is the theme name.
#       But when it's an actual wallpaper, then it's the full path
# Right now templates assumes a theme is used; ergo:
#    wallust theme -s rose-pine-dawn --templates-dir ~/code/dotfiles
#    NOTE: You can edit this with the cs mode

# Another option is to not use wallust templating for this and make a little CLI tool
# that does this functionality for us https://codeberg.org/explosion-mental/wallust/src/branch/master/src/template.rs
# so you can customize things like templating the wallpaper & theme; loading variables from the wallust
# cache (or let wallust template a single file that gets loaded by this)
#
# but perhaps we start with getting something working

# Safe to template, dedicated theme files
# config/hypr/hyprland.conf <<-- https://github.com/rose-pine/hyprland
#      (introduce a wallust.conf for variables)
# config/rofi/themes/rose_drun.rasi <<-- https://github.com/rose-pine/rofi
#      (Replace with wallust.rasi)
# config/waybar/theme.css <<-- https://github.com/rose-pine/waybar
#      (Replace with wallust.css)
# config/dunst/dunstrc.d/theme.conf <<-- colors
#      (Replace with wallust.conf, move non-theming into dunstrc)
# config/btop/themes <<--- https://github.com/rose-pine/btop
#      (Create wallust.theme)
# config/kitty/current-theme.conf <<--- Color (https://github.com/rose-pine/kitty)
#      (Create wallust.conf template)
# yazi -> https://yazi-rs.github.io/docs/configuration/theme
#      (Create a templated flavor https://github.com/yazi-rs/flavors, then customize rest in theme.toml)
# fzf -> https://github.com/rose-pine/fzf
#      (Create a file to source in zshrc if present)
# Terminal sequences:
#   - Either `-s` to not set sequences for terminal (rely on kitty theme)
#   - or `cat ~/.cache/wallust/sequences` in like `zshrc` or something

# Would require templating over / tpl also homes actual configs
# config/starship.toml <<--- colors+palette thing (https://github.com/rose-pine/starship/tree/main)

### If using a wallpaper we could
# config/hypr/hyprlock.conf <<-- {{wallpaper}}
# config/hypr/hyprpaper.conf <<-- {{wallpaper}}

### If using a theme we could
# config/dunst/dunstrc.d/theme.conf <<-- icon_theme
# config/rofi/themes/rose_drun.rasi <<-- icon-theme
# config/helix/config.toml <<--- theme = ... (https://github.com/rose-pine/helix)

### If using a custom template tool
# Both of the above and...
# config/rofi/drun.rasi <<-- the url launcher, terminal
# config/kitty/kitty.conf <<-- Fonts
# config/waybar/style.css <<-- Fonts
# config/hypr/hyprlock.conf <<-- Fonts
# config/dunst/dunstrc.d/theme.conf <<-- Fonts
# config/rofi/themes/rose_drun.rasi <<-- background-image, font


### EX:
# test = {src = "test.tpl", dst = "~/code/dotfiles/config/test.tpl"}
  
