format = """($kubernetes\n)\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$golang\
$helm\
$java\
$python\
$rust\
$terraform\
$gcloud\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$shell\
$character"""

[git_status]
disabled = false
[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
[kubernetes]
disabled = false
format = '[$symbol$context \($namespace\)]($style)'
[helm]
format = '[$symbol($version )]($style)'
[docker_context]
disabled = true
[rust]
format = '[$symbol($version )]($style)'
[scala]
format = '[${symbol}(${version} )]($style)'
[terraform]
format = '[$symbol$workspace]($style)'
[golang]
format = '[$symbol($version )]($style)'
[java]
format = '[${symbol}(${version} )]($style)'
[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
[php]
disabled = true
[gcloud]
disabled = true
