include ./theme.conf
include ./${KITTY_OS}.conf
include current-theme.conf
include keys.conf

enabled_layouts splits,vertical,horizontal
startup_session ./sessions.conf

allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}

# Cursor
cursor                      none
cursor_shape                block
# cursor_underline_thickness  2.0

# Scrollback
scrollback_pager less -R --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_fill_enlarged_window yes

# Urls
open_url_with default

# Mouse & Keyboard
focus_follows_mouse yes
macos_option_as_alt yes

# Bell
enable_audio_bell no
bell_on_tab "••• "
visual_bell_duration 0.0
visual_bell_color none
window_alert_on_bell yes

#: General
# Prompt for close, to avoid sad loss of windows :cry:
confirm_os_window_close 1
tab_switch_strategy left
placement_strategy center
term xterm-kitty

# Movement
resize_debounce_time 0.1
resize_draw_strategy static
resize_in_steps no

# Templates & Symbols
tab_activity_symbol none
tab_title_template "{title}" 
active_tab_title_template none 
