inactive_text_alpha 1.0

# Font
font_size         11.0
font_family       IosevkaCustom Nerd Font Mono Extended
bold_font         IosevkaCustom Nerd Font Mono Extended Bold
italic_font       IosevkaCustom Nerd Font Mono Extended Italic
bold_italic_font  IosevkaCustom Nerd Font Mono Extended Bold Oblique

# OS Window
hide_window_decorations no

# Kitty Window
draw_minimal_borders no
draw_window_borders_for_single_window yes
window_border_width 1
window_padding_width 0
window_margin_width 2
single_window_margin_width -1
single_window_padding_width -1
window_title_bar top
window_title_bar_min_windows 2

# Tab Bar
tab_bar_min_tabs 1
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
active_tab_font_style bold-italic
inactive_tab_font_style italic

# Background
background_opacity 1.0
dynamic_background_opacity no
dim_opacity 0.75

# Url
url_style double
